plugins {
    id 'java'
    id 'application'
}

group = 'com.benfit.reports'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

test {
    useJUnitPlatform()
}

// Configuración para ejecutar los ejemplos de Composite
application {
    mainClass = 'com.patrones.Composite.CompositeExample'
}

// Tareas personalizadas para ejecutar cada ejemplo
task runCompositeExample(type: JavaExec) {
    group = 'application'
    description = 'Ejecuta el ejemplo con patrón Composite'
    classpath = sourceSets.main.runtimeClasspath
    mainClass = 'com.patrones.Composite.CompositeExample'
}

task runWithoutComposite(type: JavaExec) {
    group = 'application'
    description = 'Ejecuta el ejemplo sin patrón Composite'
    classpath = sourceSets.main.runtimeClasspath
    mainClass = 'com.patrones.Composite.WithoutComposite'
}

task runAntiPattern(type: JavaExec) {
    group = 'application'
    description = 'Ejecuta el ejemplo de anti-patrón'
    classpath = sourceSets.main.runtimeClasspath
    mainClass = 'com.patrones.Composite.AntiPattern'
}